### ISSUE TITLE
Azure Blob always download image instead preview

### ISSUE THREAD

**Issue by ruimfernandes** [symphonicc/multer-azure-blob-storage#4] opened 2018-06-04 23:45 UTC
Hi!

I'm having troubles while uploading blobs.
I'm uploading an .png image but I guess the content-type isn't being set and therefore, in portal.azure, when I press the blob's download button the result isn't expected...  I searched at this module for something like the code below but didn't find anything related.
```
{
    contentSettings: {contentType: file.mimetype}
}
```

Expected result:
 - Open the image in a new tab

Current result:
 - Opens a new tab for less than a second, starts an direct download and closes the tab

Have you ever faced this issue? Is there any workaround?

Something related on others modules
https://github.com/MantaCodeDevs/multer-azure-storage/issues/4

**Comment by Sliverb** [comment] 2018-06-05 03:27
Not yet. I shall poke around and see what i can find.

**Comment by Sliverb** [comment] 2018-06-30 18:52
Sadly, I am unable to find details around this. My best guess is it is by design for the portal. When you are fetching the image back, then I think that's when you will have the power to set the contentType to your liking. Want to have the community weigh in on this. 

You got me very curious about this, I think you should reopen the question on the azure-storage project

**Comment by markmblc** [comment] 2018-12-21 18:31
This is addressed in my pull request. Automatically set the disposition to 'inline'

https://github.com/symphonicc/multer-azure-blob-storage/pull/11

**Comment by Sliverb** [comment] 2019-03-08 21:51
Fixed by @markmblc PR

**Closed by Sliverb** 2019-03-08 21:51 UTC
